In [ ]:
import pandas as pd

df1 = pd.read_csv("000006VS_20260904-213441.csv")
df2 = pd.read_csv("000006VS_20260905-191336.csv")

FileNotFoundError: [Errno 2] No such file or directory: '000006VS_20260904-213441.csv'

In [ ]:
import pandas as pd

# Remove "/mnt/data/" from the paths
file_1 = "000006VS_20260904-213441.csv"
file_2 = "000006VS_20260905-191336.csv"

df1 = pd.read_csv(file_1)
df2 = pd.read_csv(file_2)

FileNotFoundError: [Errno 2] No such file or directory: '000006VS_20260904-213441.csv'

In [ ]:
print("===== FILE 1 =====")
print("Shape:", df1.shape)
print("\nColumns:")
print(df1.columns.tolist())

print("\nFirst 3 rows:")
display(df1.head(3))

print("\nData types:")
print(df1.dtypes)

print("\nMissing values:")
print(df1.isna().sum().sum())

print("\nCategories:")
print(df1.iloc[:, 0].tolist())


print("\n\n===== FILE 2 =====")
print("Shape:", df2.shape)
print("\nColumns:")
print(df2.columns.tolist())

print("\nFirst 3 rows:")
display(df2.head(3))

print("\nData types:")
print(df2.dtypes)

print("\nMissing values:")
print(df2.isna().sum().sum())

print("\nCategories:")
print(df2.iloc[:, 0].tolist())

===== FILE 1 =====
Shape: (6, 1)

Columns:
['Retail sale, index (2021=100) by industrial classification (NACE Rev. 2), observations and month']

First 3 rows:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Retail sale, index (2021=100) by industrial classification (NACE Rev. 2), observations and month

Data types:
Retail sale, index (2021=100) by industrial classification (NACE Rev. 2), observations and month    object
dtype: object

Missing values:
0

Categories:
['Yearly development in percent, working day adjusted, constant prices 2026M07', '3.6', '9.6', '5.9', '1.6', '23.3']


===== FILE 2 =====
Shape: (6, 1)

Columns:
['Retail sale, index (2021=100) by industrial classification (NACE Rev. 2), observations and month']

First 3 rows:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Retail sale, index (2021=100) by industrial classification (NACE Rev. 2), observations and month

Data types:
Retail sale, index (2021=100) by industrial classification (NACE Rev. 2), observations and month    object
dtype: object

Missing values:
0

Categories:
['Yearly development in percent, working day adjusted, constant prices 2026M07', '3.6', '9.6', '5.9', '1.6', '23.3']

In [ ]:
pd.read_csv(file_1)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Retail sale, index (2021=100) by industrial classification (NACE Rev. 2), observations and month

In [ ]:


print("FILE 1:", df1.shape)
print("FILE 2:", df2.shape)

print("\nFILE 1 columns:")
print(df1.columns.tolist())

print("\nFILE 2 columns:")
print(df2.columns.tolist())

FILE 1: (6, 1)
FILE 2: (6, 1)

FILE 1 columns:
['Retail sale, index (2021=100) by industrial classification (NACE Rev. 2), observations and month']

FILE 2 columns:
['Retail sale, index (2021=100) by industrial classification (NACE Rev. 2), observations and month']

In [ ]:
# New correct paths for Colab
files = [
    "000006VS_20260904-213441.csv",
    "000006VS_20260905-191336.csv"
]

In [ ]:
import os

print(os.listdir("/content"))

['.config', '000006VS_20260905-191336.csv', '000006VS_20260904-213441.csv', 'sample_data']

In [ ]:
import os

files = [
    "/content/000006VS_20260904-213441.csv",
    "/content/000006VS_20260905-191336.csv"
]

for file in files:
    print("\n" + "=" * 100)
    print(os.path.basename(file))
    print("=" * 100)

    with open(file, "r", encoding="utf-8-sig") as f:
        for i in range(5):
            line = f.readline()
            print(f"RAW LINE {i+1}:")
            print(repr(line))

====================================================================================================
000006VS_20260904-213441.csv
====================================================================================================
RAW LINE 1:
'"Retail sale, index (2021=100) by industrial classification (NACE Rev. 2), observations and month"\n'
RAW LINE 2:
'\n'
RAW LINE 3:
'"industrial classification (NACE Rev. 2)","Constant prices 2018M01","Constant prices 2018M02","Constant prices 2018M03","Constant prices 2018M04","Constant prices 2018M05","Constant prices 2018M06","Constant prices 2018M07","Constant prices 2018M08","Constant prices 2018M09","Constant prices 2018M10","Constant prices 2018M11","Constant prices 2018M12","Constant prices 2019M01","Constant prices 2019M02","Constant prices 2019M03","Constant prices 2019M04","Constant prices 2019M05","Constant prices 2019M06","Constant prices 2019M07","Constant prices 2019M08","Constant prices 2019M09","Constant prices 2019M10","Constant prices 2019M11","Constant prices 2019M12","Constant prices 2020M01","Constant prices 2020M02","Constant prices 2020M03","Constant prices 2020M04","Constant prices 2020M05","Constant prices 2020M06","Constant prices 2020M07","Constant prices 2020M08","Constant prices 2020M09","Constant prices 2020M10","Constant prices 2020M11","Constant prices 2020M12","Constant prices 2021M01","Constant prices 2021M02","Constant prices 2021M03","Constant prices 2021M04","Constant prices 2021M05","Constant prices 2021M06","Constant prices 2021M07","Constant prices 2021M08","Constant prices 2021M09","Constant prices 2021M10","Constant prices 2021M11","Constant prices 2021M12","Constant prices 2022M01","Constant prices 2022M02","Constant prices 2022M03","Constant prices 2022M04","Constant prices 2022M05","Constant prices 2022M06","Constant prices 2022M07","Constant prices 2022M08","Constant prices 2022M09","Constant prices 2022M10","Constant prices 2022M11","Constant prices 2022M12","Constant prices 2023M01","Constant prices 2023M02","Constant prices 2023M03","Constant prices 2023M04","Constant prices 2023M05","Constant prices 2023M06","Constant prices 2023M07","Constant prices 2023M08","Constant prices 2023M09","Constant prices 2023M10","Constant prices 2023M11","Constant prices 2023M12","Constant prices 2024M01","Constant prices 2024M02","Constant prices 2024M03","Constant prices 2024M04","Constant prices 2024M05","Constant prices 2024M06","Constant prices 2024M07","Constant prices 2024M08","Constant prices 2024M09","Constant prices 2024M10","Constant prices 2024M11","Constant prices 2024M12","Constant prices 2025M01","Constant prices 2025M02","Constant prices 2025M03","Constant prices 2025M04","Constant prices 2025M05","Constant prices 2025M06","Constant prices 2025M07","Constant prices 2025M08","Constant prices 2025M09","Constant prices 2025M10","Constant prices 2025M11","Constant prices 2025M12","Constant prices 2026M01","Constant prices 2026M02","Constant prices 2026M03","Constant prices 2026M04","Constant prices 2026M05","Constant prices 2026M06","Constant prices 2026M07","Seasonally adjusted, working day adjusted, constant prices 2018M01","Seasonally adjusted, working day adjusted, constant prices 2018M02","Seasonally adjusted, working day adjusted, constant prices 2018M03","Seasonally adjusted, working day adjusted, constant prices 2018M04","Seasonally adjusted, working day adjusted, constant prices 2018M05","Seasonally adjusted, working day adjusted, constant prices 2018M06","Seasonally adjusted, working day adjusted, constant prices 2018M07","Seasonally adjusted, working day adjusted, constant prices 2018M08","Seasonally adjusted, working day adjusted, constant prices 2018M09","Seasonally adjusted, working day adjusted, constant prices 2018M10","Seasonally adjusted, working day adjusted, constant prices 2018M11","Seasonally adjusted, working day adjusted, constant prices 2018M12","Seasonally adjusted, working day adjusted, constant prices 2019M01","Seasonally adjusted, working day adjusted, constant prices 2019M02","Seasonally adjusted, working day adjusted, constant prices 2019M03","Seasonally adjusted, working day adjusted, constant prices 2019M04","Seasonally adjusted, working day adjusted, constant prices 2019M05","Seasonally adjusted, working day adjusted, constant prices 2019M06","Seasonally adjusted, working day adjusted, constant prices 2019M07","Seasonally adjusted, working day adjusted, constant prices 2019M08","Seasonally adjusted, working day adjusted, constant prices 2019M09","Seasonally adjusted, working day adjusted, constant prices 2019M10","Seasonally adjusted, working day adjusted, constant prices 2019M11","Seasonally adjusted, working day adjusted, constant prices 2019M12","Seasonally adjusted, working day adjusted, constant prices 2020M01","Seasonally adjusted, working day adjusted, constant prices 2020M02","Seasonally adjusted, working day adjusted, constant prices 2020M03","Seasonally adjusted, working day adjusted, constant prices 2020M04","Seasonally adjusted, working day adjusted, constant prices 2020M05","Seasonally adjusted, working day adjusted, constant prices 2020M06","Seasonally adjusted, working day adjusted, constant prices 2020M07","Seasonally adjusted, working day adjusted, constant prices 2020M08","Seasonally adjusted, working day adjusted, constant prices 2020M09","Seasonally adjusted, working day adjusted, constant prices 2020M10","Seasonally adjusted, working day adjusted, constant prices 2020M11","Seasonally adjusted, working day adjusted, constant prices 2020M12","Seasonally adjusted, working day adjusted, constant prices 2021M01","Seasonally adjusted, working day adjusted, constant prices 2021M02","Seasonally adjusted, working day adjusted, constant prices 2021M03","Seasonally adjusted, working day adjusted, constant prices 2021M04","Seasonally adjusted, working day adjusted, constant prices 2021M05","Seasonally adjusted, working day adjusted, constant prices 2021M06","Seasonally adjusted, working day adjusted, constant prices 2021M07","Seasonally adjusted, working day adjusted, constant prices 2021M08","Seasonally adjusted, working day adjusted, constant prices 2021M09","Seasonally adjusted, working day adjusted, constant prices 2021M10","Seasonally adjusted, working day adjusted, constant prices 2021M11","Seasonally adjusted, working day adjusted, constant prices 2021M12","Seasonally adjusted, working day adjusted, constant prices 2022M01","Seasonally adjusted, working day adjusted, constant prices 2022M02","Seasonally adjusted, working day adjusted, constant prices 2022M03","Seasonally adjusted, working day adjusted, constant prices 2022M04","Seasonally adjusted, working day adjusted, constant prices 2022M05","Seasonally adjusted, working day adjusted, constant prices 2022M06","Seasonally adjusted, working day adjusted, constant prices 2022M07","Seasonally adjusted, working day adjusted, constant prices 2022M08","Seasonally adjusted, working day adjusted, constant prices 2022M09","Seasonally adjusted, working day adjusted, constant prices 2022M10","Seasonally adjusted, working day adjusted, constant prices 2022M11","Seasonally adjusted, working day adjusted, constant prices 2022M12","Seasonally adjusted, working day adjusted, constant prices 2023M01","Seasonally adjusted, working day adjusted, constant prices 2023M02","Seasonally adjusted, working day adjusted, constant prices 2023M03","Seasonally adjusted, working day adjusted, constant prices 2023M04","Seasonally adjusted, working day adjusted, constant prices 2023M05","Seasonally adjusted, working day adjusted, constant prices 2023M06","Seasonally adjusted, working day adjusted, constant prices 2023M07","Seasonally adjusted, working day adjusted, constant prices 2023M08","Seasonally adjusted, working day adjusted, constant prices 2023M09","Seasonally adjusted, working day adjusted, constant prices 2023M10","Seasonally adjusted, working day adjusted, constant prices 2023M11","Seasonally adjusted, working day adjusted, constant prices 2023M12","Seasonally adjusted, working day adjusted, constant prices 2024M01","Seasonally adjusted, working day adjusted, constant prices 2024M02","Seasonally adjusted, working day adjusted, constant prices 2024M03","Seasonally adjusted, working day adjusted, constant prices 2024M04","Seasonally adjusted, working day adjusted, constant prices 2024M05","Seasonally adjusted, working day adjusted, constant prices 2024M06","Seasonally adjusted, working day adjusted, constant prices 2024M07","Seasonally adjusted, working day adjusted, constant prices 2024M08","Seasonally adjusted, working day adjusted, constant prices 2024M09","Seasonally adjusted, working day adjusted, constant prices 2024M10","Seasonally adjusted, working day adjusted, constant prices 2024M11","Seasonally adjusted, working day adjusted, constant prices 2024M12","Seasonally adjusted, working day adjusted, constant prices 2025M01","Seasonally adjusted, working day adjusted, constant prices 2025M02","Seasonally adjusted, working day adjusted, constant prices 2025M03","Seasonally adjusted, working day adjusted, constant prices 2025M04","Seasonally adjusted, working day adjusted, constant prices 2025M05","Seasonally adjusted, working day adjusted, constant prices 2025M06","Seasonally adjusted, working day adjusted, constant prices 2025M07","Seasonally adjusted, working day adjusted, constant prices 2025M08","Seasonally adjusted, working day adjusted, constant prices 2025M09","Seasonally adjusted, working day adjusted, constant prices 2025M10","Seasonally adjusted, working day adjusted, constant prices 2025M11","Seasonally adjusted, working day adjusted, constant prices 2025M12","Seasonally adjusted, working day adjusted, constant prices 2026M01","Seasonally adjusted, working day adjusted, constant prices 2026M02","Seasonally adjusted, working day adjusted, constant prices 2026M03","Seasonally adjusted, working day adjusted, constant prices 2026M04","Seasonally adjusted, working day adjusted, constant prices 2026M05","Seasonally adjusted, working day adjusted, constant prices 2026M06","Seasonally adjusted, working day adjusted, constant prices 2026M07","Yearly development in percent, working day adjusted, constant prices 2018M01","Yearly development in percent, working day adjusted, constant prices 2018M02","Yearly development in percent, working day adjusted, constant prices 2018M03","Yearly development in percent, working day adjusted, constant prices 2018M04","Yearly development in percent, working day adjusted, constant prices 2018M05","Yearly development in percent, working day adjusted, constant prices 2018M06","Yearly development in percent, working day adjusted, constant prices 2018M07","Yearly development in percent, working day adjusted, constant prices 2018M08","Yearly development in percent, working day adjusted, constant prices 2018M09","Yearly development in percent, working day adjusted, constant prices 2018M10","Yearly development in percent, working day adjusted, constant prices 2018M11","Yearly development in percent, working day adjusted, constant prices 2018M12","Yearly development in percent, working day adjusted, constant prices 2019M01","Yearly development in percent, working day adjusted, constant prices 2019M02","Yearly development in percent, working day adjusted, constant prices 2019M03","Yearly development in percent, working day adjusted, constant prices 2019M04","Yearly development in percent, working day adjusted, constant prices 2019M05","Yearly development in percent, working day adjusted, constant prices 2019M06","Yearly development in percent, working day adjusted, constant prices 2019M07","Yearly development in percent, working day adjusted, constant prices 2019M08","Yearly development in percent, working day adjusted, constant prices 2019M09","Yearly development in percent, working day adjusted, constant prices 2019M10","Yearly development in percent, working day adjusted, constant prices 2019M11","Yearly development in percent, working day adjusted, constant prices 2019M12","Yearly development in percent, working day adjusted, constant prices 2020M01","Yearly development in percent, working day adjusted, constant prices 2020M02","Yearly development in percent, working day adjusted, constant prices 2020M03","Yearly development in percent, working day adjusted, constant prices 2020M04","Yearly development in percent, working day adjusted, constant prices 2020M05","Yearly development in percent, working day adjusted, constant prices 2020M06","Yearly development in percent, working day adjusted, constant prices 2020M07","Yearly development in percent, working day adjusted, constant prices 2020M08","Yearly development in percent, working day adjusted, constant prices 2020M09","Yearly development in percent, working day adjusted, constant prices 2020M10","Yearly development in percent, working day adjusted, constant prices 2020M11","Yearly development in percent, working day adjusted, constant prices 2020M12","Yearly development in percent, working day adjusted, constant prices 2021M01","Yearly development in percent, working day adjusted, constant prices 2021M02","Yearly development in percent, working day adjusted, constant prices 2021M03","Yearly development in percent, working day adjusted, constant prices 2021M04","Yearly development in percent, working day adjusted, constant prices 2021M05","Yearly development in percent, working day adjusted, constant prices 2021M06","Yearly development in percent, working day adjusted, constant prices 2021M07","Yearly development in percent, working day adjusted, constant prices 2021M08","Yearly development in percent, working day adjusted, constant prices 2021M09","Yearly development in percent, working day adjusted, constant prices 2021M10","Yearly development in percent, working day adjusted, constant prices 2021M11","Yearly development in percent, working day adjusted, constant prices 2021M12","Yearly development in percent, working day adjusted, constant prices 2022M01","Yearly development in percent, working day adjusted, constant prices 2022M02","Yearly development in percent, working day adjusted, constant prices 2022M03","Yearly development in percent, working day adjusted, constant prices 2022M04","Yearly development in percent, working day adjusted, constant prices 2022M05","Yearly development in percent, working day adjusted, constant prices 2022M06","Yearly development in percent, working day adjusted, constant prices 2022M07","Yearly development in percent, working day adjusted, constant prices 2022M08","Yearly development in percent, working day adjusted, constant prices 2022M09","Yearly development in percent, working day adjusted, constant prices 2022M10","Yearly development in percent, working day adjusted, constant prices 2022M11","Yearly development in percent, working day adjusted, constant prices 2022M12","Yearly development in percent, working day adjusted, constant prices 2023M01","Yearly development in percent, working day adjusted, constant prices 2023M02","Yearly development in percent, working day adjusted, constant prices 2023M03","Yearly development in percent, working day adjusted, constant prices 2023M04","Yearly development in percent, working day adjusted, constant prices 2023M05","Yearly development in percent, working day adjusted, constant prices 2023M06","Yearly development in percent, working day adjusted, constant prices 2023M07","Yearly development in percent, working day adjusted, constant prices 2023M08","Yearly development in percent, working day adjusted, constant prices 2023M09","Yearly development in percent, working day adjusted, constant prices 2023M10","Yearly development in percent, working day adjusted, constant prices 2023M11","Yearly development in percent, working day adjusted, constant prices 2023M12","Yearly development in percent, working day adjusted, constant prices 2024M01","Yearly development in percent, working day adjusted, constant prices 2024M02","Yearly development in percent, working day adjusted, constant prices 2024M03","Yearly development in percent, working day adjusted, constant prices 2024M04","Yearly development in percent, working day adjusted, constant prices 2024M05","Yearly development in percent, working day adjusted, constant prices 2024M06","Yearly development in percent, working day adjusted, constant prices 2024M07","Yearly development in percent, working day adjusted, constant prices 2024M08","Yearly development in percent, working day adjusted, constant prices 2024M09","Yearly development in percent, working day adjusted, constant prices 2024M10","Yearly development in percent, working day adjusted, constant prices 2024M11","Yearly development in percent, working day adjusted, constant prices 2024M12","Yearly development in percent, working day adjusted, constant prices 2025M01","Yearly development in percent, working day adjusted, constant prices 2025M02","Yearly development in percent, working day adjusted, constant prices 2025M03","Yearly development in percent, working day adjusted, constant prices 2025M04","Yearly development in percent, working day adjusted, constant prices 2025M05","Yearly development in percent, working day adjusted, constant prices 2025M06","Yearly development in percent, working day adjusted, constant prices 2025M07","Yearly development in percent, working day adjusted, constant prices 2025M08","Yearly development in percent, working day adjusted, constant prices 2025M09","Yearly development in percent, working day adjusted, constant prices 2025M10","Yearly development in percent, working day adjusted, constant prices 2025M11","Yearly development in percent, working day adjusted, constant prices 2025M12","Yearly development in percent, working day adjusted, constant prices 2026M01","Yearly development in percent, working day adjusted, constant prices 2026M02","Yearly development in percent, working day adjusted, constant prices 2026M03","Yearly development in percent, working day adjusted, constant prices 2026M04","Yearly development in percent, working day adjusted, constant prices 2026M05","Yearly development in percent, working day adjusted, constant prices 2026M06","Yearly development in percent, working day adjusted, constant prices 2026M07"\n'
RAW LINE 4:
'"47.11+47.2 retail sale with mostly food",..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,85.5,82.3,93.1,93.8,97.2,103.9,99.6,97.2,90.4,91.6,90.5,107.9,87.2,87.1,99.1,91.0,99.8,101.7,100.9,98.8,89.5,93.4,92.1,108.5,88.5,84.3,92.5,98.2,97.9,100.3,102.2,98.0,90.8,95.0,91.3,109.3,88.9,84.1,96.5,99.0,101.5,106.2,107.2,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,94.7,93.4,93.6,93.9,94.6,95.3,95.0,94.8,94.4,95.0,94.4,94.9,95.4,95.5,95.4,95.1,95.9,95.7,94.7,95.2,95.8,95.6,95.0,96.6,95.7,95.8,95.5,96.8,94.0,94.4,95.8,95.7,95.9,96.1,96.5,96.1,96.2,95.7,97.3,99.9,98.7,98.8,99.2,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,0.6,2.2,1.8,1.4,1.3,0.4,0.0,0.4,1.6,0.6,0.6,1.8,0.3,0.2,0.0,2.0,-1.9,-1.4,1.3,0.4,0.1,0.4,1.5,-0.5,0.5,-0.2,1.8,3.2,5.1,4.5,3.6\n'
RAW LINE 5:

In [ ]:
import pandas as pd

file_1 = "/content/000006VS_20260904-213441.csv"
file_2 = "/content/000006VS_20260905-191336.csv"

df1 = pd.read_csv(file_1, skiprows=2)
df2 = pd.read_csv(file_2, skiprows=2)

print("FILE 1 shape:", df1.shape)
print("FILE 2 shape:", df2.shape)

print("\nFILE 1 — first 3 rows:")
display(df1.head(3))

print("\nFILE 2 — first 3 rows:")
display(df2.head(3))

FILE 1 shape: (5, 310)
FILE 2 shape: (5, 418)

FILE 1 — first 3 rows:

,industrial classification (NACE Rev. 2),Constant prices 2018M01,Constant prices 2018M02,Constant prices 2018M03,Constant prices 2018M04,Constant prices 2018M05,Constant prices 2018M06,Constant prices 2018M07,Constant prices 2018M08,Constant prices 2018M09,...,"Yearly development in percent, working day adjusted, constant prices 2025M10","Yearly development in percent, working day adjusted, constant prices 2025M11","Yearly development in percent, working day adjusted, constant prices 2025M12","Yearly development in percent, working day adjusted, constant prices 2026M01","Yearly development in percent, working day adjusted, constant prices 2026M02","Yearly development in percent, working day adjusted, constant prices 2026M03","Yearly development in percent, working day adjusted, constant prices 2026M04","Yearly development in percent, working day adjusted, constant prices 2026M05","Yearly development in percent, working day adjusted, constant prices 2026M06","Yearly development in percent, working day adjusted, constant prices 2026M07"
0,47.11+47.2 retail sale with mostly food,..,..,..,..,..,..,..,..,..,...,0.4,1.5,-0.5,0.5,-0.2,1.8,3.2,5.1,4.5,3.6
1,47.591-47.592 specialised stores for home furn...,96.6,82.1,95.3,91.1,83.4,85.7,90.1,102.3,95.1,...,6.3,7.1,5.2,7.1,1.9,8.3,4.5,9.4,9.0,9.6
2,47.64 sports shops,66.9,67.5,77.0,98.4,104.9,96.2,102.7,104.4,79.3,...,0.1,-1.6,-4.5,6.9,3.8,3.8,-0.1,8.5,7.7,5.9

FILE 2 — first 3 rows:

,industrial classification (NACE Rev. 2),Constant prices 2015M01,Constant prices 2015M02,Constant prices 2015M03,Constant prices 2015M04,Constant prices 2015M05,Constant prices 2015M06,Constant prices 2015M07,Constant prices 2015M08,Constant prices 2015M09,...,"Yearly development in percent, working day adjusted, constant prices 2025M10","Yearly development in percent, working day adjusted, constant prices 2025M11","Yearly development in percent, working day adjusted, constant prices 2025M12","Yearly development in percent, working day adjusted, constant prices 2026M01","Yearly development in percent, working day adjusted, constant prices 2026M02","Yearly development in percent, working day adjusted, constant prices 2026M03","Yearly development in percent, working day adjusted, constant prices 2026M04","Yearly development in percent, working day adjusted, constant prices 2026M05","Yearly development in percent, working day adjusted, constant prices 2026M06","Yearly development in percent, working day adjusted, constant prices 2026M07"
0,47.11+47.2 retail sale with mostly food,..,..,..,..,..,..,..,..,..,...,0.4,1.5,-0.5,0.5,-0.2,1.8,3.2,5.1,4.5,3.6
1,47.591-47.592 specialised stores for home furn...,81.4,68.9,80.8,78.6,81.0,82.6,93.7,84.1,85.6,...,6.3,7.1,5.2,7.1,1.9,8.3,4.5,9.4,9.0,9.6
2,47.64 sports shops,62.5,59.9,80.9,88.5,90.4,92.3,103.6,87.8,75.9,...,0.1,-1.6,-4.5,6.9,3.8,3.8,-0.1,8.5,7.7,5.9

In [ ]:
# Basic structural validation

print("FILE 1")
print("Categories:")
print(df1.iloc[:, 0].tolist())

print("\nNumber of columns:", len(df1.columns))

print("\nFILE 2")
print("Categories:")
print(df2.iloc[:, 0].tolist())

print("\nNumber of columns:", len(df2.columns))

# Check for missing/suppressed values
print("\nMissing/suppressed values:")
print("File 1:", (df1 == "..").sum().sum())
print("File 2:", (df2 == "..").sum().sum())

# Check duplicate column names
print("\nDuplicate column names:")
print("File 1:", df1.columns.duplicated().sum())
print("File 2:", df2.columns.duplicated().sum())

FILE 1
Categories:
['47.11+47.2 retail sale with mostly food', '47.591-47.592 specialised stores for home furniture; specialised stores for office furniture', '47.64 sports shops', '47.71 clothing stores', '47.74+47.75 retail sale of medical, cosmetic and toilet articles']

Number of columns: 310

FILE 2
Categories:
['47.11+47.2 retail sale with mostly food', '47.591-47.592 specialised stores for home furniture; specialised stores for office furniture', '47.64 sports shops', '47.71 clothing stores', '47.74+47.75 retail sale of medical, cosmetic and toilet articles']

Number of columns: 418

Missing/suppressed values:
File 1: 192
File 2: 300

Duplicate column names:
File 1: 0
File 2: 0

In [ ]:
# Compare overlapping columns between File 1 and File 2

overlap_columns = [col for col in df1.columns if col in df2.columns]

print("Number of overlapping columns:", len(overlap_columns))

# Compare the actual values
comparison = df1[overlap_columns].astype(str).equals(
    df2[overlap_columns].astype(str)
)

print("Are all overlapping values identical?:", comparison)

Number of overlapping columns: 310
Are all overlapping values identical?: True

In [ ]:
# If they are not identical, identify where the differences are

if not comparison:
    differences = []

    for col in overlap_columns:
        if not df1[col].astype(str).equals(df2[col].astype(str)):
            differences.append(col)

    print("Number of columns with differences:", len(differences))
    print("\nFirst 20 columns with differences:")
    print(differences[:20])

In [ ]:
# Identify the three observation groups in the full historical file

observation_types = {}

for col in df2.columns[1:]:
    observation_type = col.rsplit(" ", 1)[0]
    observation_types[observation_type] = observation_types.get(observation_type, 0) + 1

for observation_type, count in observation_types.items():
    print(f"{observation_type}: {count} columns")

Constant prices: 139 columns
Seasonally adjusted, working day adjusted, constant prices: 139 columns
Yearly development in percent, working day adjusted, constant prices: 139 columns

In [ ]:
# Show the first and last column belonging to each observation group

for observation_type in observation_types:
    matching_columns = [
        col for col in df2.columns
        if col.startswith(observation_type)
    ]

    print(f"\n{observation_type}")
    print("First:", matching_columns[0])
    print("Last: ", matching_columns[-1])

Constant prices
First: Constant prices 2015M01
Last:  Constant prices 2026M07

Seasonally adjusted, working day adjusted, constant prices
First: Seasonally adjusted, working day adjusted, constant prices 2015M01
Last:  Seasonally adjusted, working day adjusted, constant prices 2026M07

Yearly development in percent, working day adjusted, constant prices
First: Yearly development in percent, working day adjusted, constant prices 2015M01
Last:  Yearly development in percent, working day adjusted, constant prices 2026M07

In [ ]:
# Reshape File 2 from wide format to long format

id_column = df2.columns[0]

df_long = df2.melt(
    id_vars=id_column,
    var_name="observation_month",
    value_name="value"
)

print("Long-format shape:", df_long.shape)

print("\nFirst 10 rows:")
display(df_long.head(10))

Long-format shape: (2085, 3)

First 10 rows:

,industrial classification (NACE Rev. 2),observation_month,value
0,47.11+47.2 retail sale with mostly food,Constant prices 2015M01,..
1,47.591-47.592 specialised stores for home furn...,Constant prices 2015M01,81.4
2,47.64 sports shops,Constant prices 2015M01,62.5
3,47.71 clothing stores,Constant prices 2015M01,106.3
4,"47.74+47.75 retail sale of medical, cosmetic a...",Constant prices 2015M01,65.4
5,47.11+47.2 retail sale with mostly food,Constant prices 2015M02,..
6,47.591-47.592 specialised stores for home furn...,Constant prices 2015M02,68.9
7,47.64 sports shops,Constant prices 2015M02,59.9
8,47.71 clothing stores,Constant prices 2015M02,84.9
9,"47.74+47.75 retail sale of medical, cosmetic a...",Constant prices 2015M02,64.2

In [ ]:
# Split observation type and month

df_long["observation_type"] = df_long["observation_month"].str.extract(
    r"^(.*?)\s+(\d{4}M\d{2})$"
)[0]

df_long["month"] = df_long["observation_month"].str.extract(
    r"(\d{4}M\d{2})$"
)[0]

print("Observation types:")
print(df_long["observation_type"].unique())

print("\nNumber of observation types:", df_long["observation_type"].nunique())

print("\nNumber of months:", df_long["month"].nunique())

print("\nMonth range:")
print(df_long["month"].min(), "to", df_long["month"].max())

print("\nFirst 10 rows:")
display(df_long.head(10))

Observation types:
['Constant prices'
 'Seasonally adjusted, working day adjusted, constant prices'
 'Yearly development in percent, working day adjusted, constant prices']

Number of observation types: 3

Number of months: 139

Month range:
2015M01 to 2026M07

First 10 rows:

,industrial classification (NACE Rev. 2),observation_month,value,observation_type,month
0,47.11+47.2 retail sale with mostly food,Constant prices 2015M01,..,Constant prices,2015M01
1,47.591-47.592 specialised stores for home furn...,Constant prices 2015M01,81.4,Constant prices,2015M01
2,47.64 sports shops,Constant prices 2015M01,62.5,Constant prices,2015M01
3,47.71 clothing stores,Constant prices 2015M01,106.3,Constant prices,2015M01
4,"47.74+47.75 retail sale of medical, cosmetic a...",Constant prices 2015M01,65.4,Constant prices,2015M01
5,47.11+47.2 retail sale with mostly food,Constant prices 2015M02,..,Constant prices,2015M02
6,47.591-47.592 specialised stores for home furn...,Constant prices 2015M02,68.9,Constant prices,2015M02
7,47.64 sports shops,Constant prices 2015M02,59.9,Constant prices,2015M02
8,47.71 clothing stores,Constant prices 2015M02,84.9,Constant prices,2015M02
9,"47.74+47.75 retail sale of medical, cosmetic a...",Constant prices 2015M02,64.2,Constant prices,2015M02

In [ ]:
print("Observation types:")
print(df_long["observation_type"].unique())

print("\nNumber of observation types:")
print(df_long["observation_type"].nunique())

print("\nNumber of months:")
print(df_long["month"].nunique())

print("\nMonth range:")
print(df_long["month"].min(), "to", df_long["month"].max())

print("\nMissing extracted values:")
print("Observation type:", df_long["observation_type"].isna().sum())
print("Month:", df_long["month"].isna().sum())

Observation types:
['Constant prices'
 'Seasonally adjusted, working day adjusted, constant prices'
 'Yearly development in percent, working day adjusted, constant prices']

Number of observation types:
3

Number of months:
139

Month range:
2015M01 to 2026M07

Missing extracted values:
Observation type: 0
Month: 0

In [ ]:
# Locate all ".." values by category and observation type

missing_summary = (
    df_long[df_long["value"] == ".."]
    .groupby(["industrial classification (NACE Rev. 2)", "observation_type"])
    .size()
    .reset_index(name="missing_count")
)

display(missing_summary)

,industrial classification (NACE Rev. 2),observation_type,missing_count
0,47.11+47.2 retail sale with mostly food,Constant prices,96
1,47.11+47.2 retail sale with mostly food,"Seasonally adjusted, working day adjusted, con...",96
2,47.11+47.2 retail sale with mostly food,"Yearly development in percent, working day adj...",108

In [ ]:
# Check the earliest and latest month containing ".."

missing_rows = df_long[df_long["value"] == ".."]

print("Earliest month with '..':", missing_rows["month"].min())
print("Latest month with '..':", missing_rows["month"].max())

Earliest month with '..': 2015M01
Latest month with '..': 2023M12

In [ ]:
# Inspect the missing months for the food category
# using the forecasting series only

forecast_series = "Seasonally adjusted, working day adjusted, constant prices"

food_missing = df_long[
    (df_long["industrial classification (NACE Rev. 2)"] ==
     "47.11+47.2 retail sale with mostly food") &
    (df_long["observation_type"] == forecast_series) &
    (df_long["value"] == "..")
]

print("Number of missing months:", len(food_missing))

print("\nFirst 20 missing months:")
print(food_missing["month"].head(20).tolist())

print("\nLast 20 missing months:")
print(food_missing["month"].tail(20).tolist())

Number of missing months: 96

First 20 missing months:
['2015M01', '2015M02', '2015M03', '2015M04', '2015M05', '2015M06', '2015M07', '2015M08', '2015M09', '2015M10', '2015M11', '2015M12', '2016M01', '2016M02', '2016M03', '2016M04', '2016M05', '2016M06', '2016M07', '2016M08']

Last 20 missing months:
['2021M05', '2021M06', '2021M07', '2021M08', '2021M09', '2021M10', '2021M11', '2021M12', '2022M01', '2022M02', '2022M03', '2022M04', '2022M05', '2022M06', '2022M07', '2022M08', '2022M09', '2022M10', '2022M11', '2022M12']

In [ ]:
# Find the first and last available observation for every category and series

df_check = df_long.copy()

df_check["numeric_value"] = pd.to_numeric(
    df_check["value"],
    errors="coerce"
)

availability = (
    df_check[df_check["numeric_value"].notna()]
    .groupby([
        "industrial classification (NACE Rev. 2)",
        "observation_type"
    ])["month"]
    .agg(["min", "max", "count"])
    .reset_index()
)

display(availability)

,industrial classification (NACE Rev. 2),observation_type,min,max,count
0,47.11+47.2 retail sale with mostly food,Constant prices,2023M01,2026M07,43
1,47.11+47.2 retail sale with mostly food,"Seasonally adjusted, working day adjusted, con...",2023M01,2026M07,43
2,47.11+47.2 retail sale with mostly food,"Yearly development in percent, working day adj...",2024M01,2026M07,31
3,47.591-47.592 specialised stores for home furn...,Constant prices,2015M01,2026M07,139
4,47.591-47.592 specialised stores for home furn...,"Seasonally adjusted, working day adjusted, con...",2015M01,2026M07,139
5,47.591-47.592 specialised stores for home furn...,"Yearly development in percent, working day adj...",2015M01,2026M07,139
6,47.64 sports shops,Constant prices,2015M01,2026M07,139
7,47.64 sports shops,"Seasonally adjusted, working day adjusted, con...",2015M01,2026M07,139
8,47.64 sports shops,"Yearly development in percent, working day adj...",2015M01,2026M07,139
9,47.71 clothing stores,Constant prices,2015M01,2026M07,139
10,47.71 clothing stores,"Seasonally adjusted, working day adjusted, con...",2015M01,2026M07,139
11,47.71 clothing stores,"Yearly development in percent, working day adj...",2015M01,2026M07,139
12,"47.74+47.75 retail sale of medical, cosmetic a...",Constant prices,2015M01,2026M07,139
13,"47.74+47.75 retail sale of medical, cosmetic a...","Seasonally adjusted, working day adjusted, con...",2015M01,2026M07,139
14,"47.74+47.75 retail sale of medical, cosmetic a...","Yearly development in percent, working day adj...",2015M01,2026M07,139

In [ ]:
# Convert ".." to missing values and convert observations to numeric

df_long["value"] = pd.to_numeric(
    df_long["value"],
    errors="coerce"
)

print("Data type:", df_long["value"].dtype)

print("\nMissing values after conversion:", df_long["value"].isna().sum())

print("\nRemaining non-numeric values:")
print(df_long["value"].apply(lambda x: not pd.isna(x) and not isinstance(x, (int, float))).sum())

Data type: float64

Missing values after conversion: 300

Remaining non-numeric values:
0

In [ ]:
# Create a proper monthly date and clean the category column name

df_long["date"] = pd.to_datetime(
    df_long["month"].str.replace("M", "-") + "-01"
)

df_long = df_long.rename(
    columns={
        "industrial classification (NACE Rev. 2)": "category"
    }
)

print("Date range:")
print(df_long["date"].min(), "to", df_long["date"].max())

print("\nDate data type:")
print(df_long["date"].dtype)

print("\nColumns:")
print(df_long.columns.tolist())

print("\nFirst 5 rows:")
display(df_long.head())

Date range:
2015-01-01 00:00:00 to 2026-07-01 00:00:00

Date data type:
datetime64[ns]

Columns:
['category', 'observation_month', 'value', 'observation_type', 'month', 'date']

First 5 rows:

,category,observation_month,value,observation_type,month,date
0,47.11+47.2 retail sale with mostly food,Constant prices 2015M01,NaN,Constant prices,2015M01,2015-01-01
1,47.591-47.592 specialised stores for home furn...,Constant prices 2015M01,81.4,Constant prices,2015M01,2015-01-01
2,47.64 sports shops,Constant prices 2015M01,62.5,Constant prices,2015M01,2015-01-01
3,47.71 clothing stores,Constant prices 2015M01,106.3,Constant prices,2015M01,2015-01-01
4,"47.74+47.75 retail sale of medical, cosmetic a...",Constant prices 2015M01,65.4,Constant prices,2015M01,2015-01-01

In [ ]:
# Final structural integrity check

expected_rows = 5 * 3 * 139

print("Actual rows:", len(df_long))
print("Expected rows:", expected_rows)

print("\nCategories:", df_long["category"].nunique())
print("Observation types:", df_long["observation_type"].nunique())
print("Months:", df_long["date"].nunique())

print("\nDuplicate category-series-month combinations:")
duplicates = df_long.duplicated(
    subset=["category", "observation_type", "date"]
).sum()
print(duplicates)

print("\nRows per observation type:")
print(df_long.groupby("observation_type").size())

print("\nRows per category:")
print(df_long.groupby("category").size())

Actual rows: 2085
Expected rows: 2085

Categories: 5
Observation types: 3
Months: 139

Duplicate category-series-month combinations:
0

Rows per observation type:
observation_type
Constant prices                                                         695
Seasonally adjusted, working day adjusted, constant prices              695
Yearly development in percent, working day adjusted, constant prices    695
dtype: int64

Rows per category:
category
47.11+47.2 retail sale with mostly food                                                         417
47.591-47.592 specialised stores for home furniture; specialised stores for office furniture    417
47.64 sports shops                                                                              417
47.71 clothing stores                                                                           417
47.74+47.75 retail sale of medical, cosmetic and toilet articles                                417
dtype: int64

In [ ]:
# Finalize the clean analytical dataset

df_clean = df_long.drop(
    columns=["observation_month"]
).copy()

# Create the three analytical datasets

df_forecast = df_clean[
    df_clean["observation_type"] ==
    "Seasonally adjusted, working day adjusted, constant prices"
].copy()

df_constant = df_clean[
    df_clean["observation_type"] ==
    "Constant prices"
].copy()

df_yoy = df_clean[
    df_clean["observation_type"] ==
    "Yearly development in percent, working day adjusted, constant prices"
].copy()

print("CLEAN DATASET")
print("Shape:", df_clean.shape)
print("Columns:", df_clean.columns.tolist())

print("\nFORECAST DATASET")
print("Shape:", df_forecast.shape)
print("Missing values:", df_forecast["value"].isna().sum())

print("\nCONSTANT-PRICE DATASET")
print("Shape:", df_constant.shape)
print("Missing values:", df_constant["value"].isna().sum())

print("\nYOY DATASET")
print("Shape:", df_yoy.shape)
print("Missing values:", df_yoy["value"].isna().sum())

CLEAN DATASET
Shape: (2085, 5)
Columns: ['category', 'value', 'observation_type', 'month', 'date']

FORECAST DATASET
Shape: (695, 5)
Missing values: 96

CONSTANT-PRICE DATASET
Shape: (695, 5)
Missing values: 96

YOY DATASET
Shape: (695, 5)
Missing values: 108

In [ ]:
import pandas as pd
from google.colab import files

# Load the validated source-of-truth file
file_2 = "/content/000006VS_20260905-191336.csv"

df2 = pd.read_csv(file_2, skiprows=2)

# Reshape wide → long
id_column = df2.columns[0]

df_long = df2.melt(
    id_vars=id_column,
    var_name="observation_month",
    value_name="value"
)

# Separate observation type and month
df_long["observation_type"] = df_long["observation_month"].str.extract(
    r"^(.*?)\s+(\d{4}M\d{2})$"
)[0]

df_long["month"] = df_long["observation_month"].str.extract(
    r"(\d{4}M\d{2})$"
)[0]

# Convert ".." to NaN and values to numeric
df_long["value"] = pd.to_numeric(
    df_long["value"],
    errors="coerce"
)

# Create proper date
df_long["date"] = pd.to_datetime(
    df_long["month"].str.replace("M", "-") + "-01"
)

# Rename category column
df_long = df_long.rename(
    columns={
        "industrial classification (NACE Rev. 2)": "category"
    }
)

# Remove temporary combined column
df_clean = df_long.drop(
    columns=["observation_month"]
).copy()

# Final validation
print("Shape:", df_clean.shape)
print("Missing values:", df_clean["value"].isna().sum())
print("Duplicate rows:", df_clean.duplicated(
    subset=["category", "observation_type", "date"]
).sum())

# Export
output_file = "/content/swedish_retail_demand_clean.csv"

df_clean.to_csv(output_file, index=False)

print("\nFile created:", output_file)

# Download
files.download(output_file)

FileNotFoundError: [Errno 2] No such file or directory: '/content/000006VS_20260905-191336.csv'

In [ ]:
import os

print(os.listdir("/content"))

['.config', 'sample_data']

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving 000006VS_20260905-191336.csv to 000006VS_20260905-191336.csv

In [ ]:
import os

print(os.listdir("/content"))

['.config', '000006VS_20260905-191336.csv', 'sample_data']

In [ ]:
import pandas as pd
from google.colab import files

# Source-of-truth SCB file
file_2 = "/content/000006VS_20260905-191336.csv"

# 1. Load
df2 = pd.read_csv(file_2, skiprows=2)

# 2. Wide → long
id_column = df2.columns[0]

df_long = df2.melt(
    id_vars=id_column,
    var_name="observation_month",
    value_name="value"
)

# 3. Separate observation type and month
df_long["observation_type"] = df_long["observation_month"].str.extract(
    r"^(.*?)\s+(\d{4}M\d{2})$"
)[0]

df_long["month"] = df_long["observation_month"].str.extract(
    r"(\d{4}M\d{2})$"
)[0]

# 4. Convert values
df_long["value"] = pd.to_numeric(
    df_long["value"],
    errors="coerce"
)

# 5. Create proper date
df_long["date"] = pd.to_datetime(
    df_long["month"].str.replace("M", "-") + "-01"
)

# 6. Rename category
df_long = df_long.rename(
    columns={
        "industrial classification (NACE Rev. 2)": "category"
    }
)

# 7. Remove temporary column
df_clean = df_long.drop(
    columns=["observation_month"]
).copy()

# 8. Final validation
print("Shape:", df_clean.shape)
print("Missing values:", df_clean["value"].isna().sum())
print(
    "Duplicate category-series-month combinations:",
    df_clean.duplicated(
        subset=["category", "observation_type", "date"]
    ).sum()
)

# 9. Export clean dataset
output_file = "/content/swedish_retail_demand_clean.csv"

df_clean.to_csv(output_file, index=False)

print("\nCreated:", output_file)

# 10. Download
files.download(output_file)

Shape: (2085, 5)
Missing values: 300
Duplicate category-series-month combinations: 0

Created: /content/swedish_retail_demand_clean.csv